typography_spectrum: 0.93805
color:
  brandColors:
    - '#050708'
    - '#ffffff'
    - '#9d9b9b'
    - '#555354'
    - '#b0b1b1'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.06501
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: Adriana Velinova
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
navigation:
  - id: dd4f862b-3095-41a5-8b60-b9459dbb736d
    name: Gallery
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5829005d-f1c9-44cd-85e8-90b8c1aaf701.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
